# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template
spring.application.name=EasyTraza

spring.datasource.url=jdbc:mysql://localhost:3306/easytraza?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8443

server.ssl.enabled=true
server.ssl.key-store=classpath:easytraza.p12
server.ssl.key-store-password=123456
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=easytraza

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-part-count=200

#mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jove.naranjo.oriol@alumnat.copernic.cat
spring.mail.password=xrtb dbpp eniu fmdv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
app.base-url=https://192.168.1.88:8443

#Suspendre sessi\u00f3
server.servlet.session.timeout=30m
#superAdmin
app.superadmin.email=superadmin@easytraza.com
